// central place for API endpoints. Edit here to add/remove modules
export const apiModules = [
{ name: 'Battery & Tyre', 
  upload: '/api/battery_tyre/upload', 
  get: '/api/battery_tyre/getallbattery_tyre',
  getByMonthYear: '/api/battery_tyre/getbattery_tyre',
  deleteAll: "/api/battery_tyre/delete_all",
},
{ name: 'BR Conversion', 
  upload: '/api/br_conversion/upload', 
  get: '/api/br_conversion/getallbr_conversion',
  getByMonthYear :'/api/br_conversion/getbr_conversion',
  deleteAll: "/api/br_conversion/delete_all",
},
{ name: 'Due Done', 
  upload: '/api/due_done/upload', 
  get: '/api/due_done/getalldue_done',
  getByMonthYear :'/api/due_done/getdue_done',
  deleteAll: "/api/due_done/delete_all",
},

{ name: 'Hold Up', 
  upload: '/api/hold_up/upload', 
  get: '/api/hold_up/getallhold_up',
  getByMonthYear :'/api/hold_up/gethold_up',
  deleteAll: "/api/hold_up/delete_all",
},
{ name: 'Labour', 
  upload: '/api/labour/upload', 
  get: '/api/labour/getalllabour',
  getByMonthYear :'/api/labour/getlabour',
  deleteAll: "/api/labour/delete_all",
},
{ name: 'Loadd', 
  upload: '/api/loadd/upload', 
  get: '/api/loadd/getallloadd',
  getByMonthYear: '/api/loadd/getloadd' ,
  deleteAll: "/api/loadd/delete_all",
},
{ name: 'MCP', 
  upload: '/api/mcp/upload', 
  get: '/api/mcp/getallmcp',
  getByMonthYear : '/api/mcp/getmcp',
  deleteAll: "/api/mcp/delete_all",
},
{ name: 'MGA', 
  upload: '/api/mga/upload',
  get: '/api/mga/getallmga',
  getByMonthYear : '/api/mga/getmga',
  deleteAll: "/api/mga/delete_all",
},
{ name: 'MGA Profit', 
  upload: '/api/mga_profit/upload',
  get: '/api/mga_profit/getallmga_profit',
  getByMonthYear : '/api/mga_profit/getmga_profit',
  deleteAll: "/api/mga_profit/delete_all",
},
{ name: 'MSGP', 
  upload: '/api/msgp/upload', 
  get: '/api/msgp/getallmsgp',
  getByMonthYear: '/api/msgp/getmsgp',
  deleteAll: "/api/msgp/delete_all",
},
{ name: 'MSGP Profit', 
  upload: '/api/msgp_profit/upload', 
  get: '/api/msgp_profit/getallmsgp_profit',
  getByMonthYear: '/api/msgp_profit/getmsgp_profit',
  deleteAll: "/api/msgp_profit/delete_all",
},
{ name: 'Oil', 
  upload: '/api/oil/upload', 
  get: '/api/oil/getalloil',
  getByMonthYear: '/api/oil/getoil',
  deleteAll: "/api/oil/delete_all",
},
{ name: 'PMS Parts',
   upload: '/api/pms_parts/upload',
    get: '/api/pms_parts/getallpms_parts',
    getByMonthYear: '/api/pms_parts/getpms_parts',
  deleteAll: "/api/pms_parts/delete_all",
},
{
  name: "Productivity",
  upload: "/api/productivity/upload",
  get: "/api/productivity/getallproductivity",
  updateServiceUtilizedBay: "/api/productivity/update_service_utilized_bay",
  updateBodyShopUtilizedBay: "/api/productivity/update_bodyshop_utilized_bay",
  updateWorkingDays: "/api/productivity/update_working_days"
}
,

{ name: 'Profit & Loss', 
  upload: '/api/profit_loss/upload', 
  get: '/api/profit_loss/getallprofit_loss',
  deleteAll: "/api/profit_loss/delete_all",
}, 

{ name: 'Referencee',
  upload: '/api/referencee/upload',
  get: '/api/referencee/getallreferencee',
  getByMonthYear: '/api/referencee/getreferencee',
  deleteAll: "/api/referencee/delete_all",
},
{ name: 'Revenue',
  upload: '/api/revenue/upload',
  get: '/api/revenue/getallrevenue',
  getByMonthYear: '/api/revenue/getrevenue',
  deleteAll: "/api/revenue/delete_all",
},
{ name: 'Spares',
  upload: '/api/spares/upload',
  get: '/api/spares/getallspares',
  getByMonthYear: '/api/spares/getspares',
  deleteAll: "/api/spares/delete_all",
},
{ name: 'TAT',
  upload: '/api/tat/upload',
  get: '/api/tat/getalltat',
  getByMonthYear: '/api/tat/gettat',
  deleteAll: "/api/tat/delete_all",
},
{ name: 'VAS',
  upload: '/api/vas/upload',
  get: '/api/vas/getallvas',
  getByMonthYear: '/api/vas/getvas',
  deleteAll: "/api/vas/delete_all",
},
];