export const uploadNavbarButtons = [
  { label: "Load", path: "/loadd-upload" },
  { label: "BR Conversion", path: "/brconversion-upload" },
  { label: "Labour", path: "/labour-upload" },
  { label: "Spares", path: "/spares-upload" },
  { label: "VAS", path: "/vas-upload" },
  { label: "MSGP", path: "/msgp-upload" },
  { label: "MSGP Profit", path: "/msgp_profit-upload" },
  { label: "Revenue", path: "/revenue-upload" },
  { label: "Oil", path: "/oil-upload" },
  { label: "Battery & Tyre", path: "/batterytyre-upload" },
  { label: "PMS Parts", path: "/pms_parts-upload" },
  { label: "MGA", path: "/mga-upload" },
  { label: "MGA Profit", path: "/mga_profit-upload" },
  { label: "TAT", path: "/tat-upload" },
  { label: "MCP", path: "/mcp-upload" },
  { label: "Reference", path: "/referencee-upload" },
  { label: "Profit & Loss", path: "/profit_loss-upload" }, 
];
